---
title: "Outline"
author: "Brendan Cullen & Krista DeStasio"
date: "5/1/2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include = FALSE}
library(janitor) 
library(tidyverse)
library(factoextra)
library(RColorBrewer)
library(DT)
knitr::opts_chunk$set(echo = TRUE)

##AC: you might want to make a note that you need to install DT and factoextra
```

# Set-up
```{r Import and clean data}
# Read in the data
pokemon_data <- clean_names(read.csv("pokemon.csv")) #AAC: Cool, I didn't know you could do the clean_names function while importing! 

#AAC: I would consider providing the reader with a description of the datasource- it looks like pokemon (: - cool data :D

# Create a data frame without missing values that contains the type1 labels
pokemon_data <- pokemon_data %>% 
    select(-percentage_male, -type2) %>%  
    filter(type1 %in% c("ghost", "fairy", "dragon")) %>%  # Let's limit this to a few pokemon #AAC: Cool use of %n%!
    mutate(type1 = droplevels(type1)) %>% # Few poke have data for these
    drop_na() #AAC: I didn't know this was a command you could use - great find!

# Create data frame with "against" variables 
pokemon_against <- pokemon_data %>% 
    select(starts_with("against"), hp)
```

# Preprocessing
```{r Missing observations}
#table(is.na(pokemon_data)) # we good
```

```{r, Zero and near-zero variance}
#caret::nearZeroVar(pokemon_numeric, saveMetrics = TRUE) # we good
```

```{r Multicollinearity}
#caret::findLinearCombos(pokemon_numeric) 

# Remove speed since it is a linear combination of other variables
#pokemon_numeric <- dplyr::select(pokemon_numeric, -speed)

#AAC: I'm a little confused what this means and why it's commented out
```

```{r Data scaling}
pokemon_against <- pokemon_against %>% 
    scale() %>% 
    as.data.frame()
```

# Run K-means clustering with variable numbers of clusters
```{r}
run_clust <- function(df, k) {
    set.seed(100)
    eclust(df,
           FUNcluster = 'kmeans',
           hc_metric = 'euclidean',
           k = k, nstart = 25, graph = TRUE)
}

#AAC: I thought it was cool how you ran a simulation/set seed WITHIN a function. Awesome use. But I'm not sure what exactly this does (I'm not familiar with eclust)
```

```{r}
rownames(pokemon_against) <- c() # need to remove rownames in order to get atomic vector output for cluster membership data

pokemon_against_km <- run_clust(pokemon_against, 6)
```

# Visualizations
```{r Silhouette plot}
set.seed(100)

# Make silhouette plot
fviz_silhouette(pokemon_against_km, palette = "jco", 
                print.summary = FALSE, 
                ggtheme = theme_minimal()) 


# Plot average silhouette width against number of clusters 
fviz_nbclust(pokemon_against, kmeans, method = "silhouette", k.max = 6) + theme_classic()

#AAC: Very cool plot (even though I am unfamiliar with what clusters are!)
```

```{r Cluster plot}
pokemon_against_km$clust_plot + 
  theme_minimal()

#AAC: The overlapping numbers of this plot are a bit hard to read
```

```{r Facet by type}
# Wrangle data to plot 
plot_data <- cbind(pokemon_against_km$cluster, pokemon_against, pokemon_data$type1) %>%  
  rename(cluster = `pokemon_against_km$cluster`,
         type = `pokemon_data$type1`) %>%
  mutate(cluster = as.character(cluster),
         type = as.character(type)) %>%
  gather(value = value, key = variable_name,-type,-cluster)

# Plot clusters by pokemon type
plot_data %>% 
    ggplot(aes(x = variable_name, y = value, color = cluster)) +
    geom_jitter(alpha = 0.6) + 
  coord_flip() +
    facet_wrap(~type) +
  theme_minimal()

#AAC: Awesome plot! Conisder making the plot y axes labels more meaningful and cleaned up
```


```{r Tables}
# number of clusters 
k <- pokemon_against_km$nbclust

# cluster number
clust_num <- map_chr(seq(1:k), ~paste("Cluster", .x)) #AAC: Good use of map

# ss-within
wss <- round(pokemon_against_km$withinss, 2)

# ss-between
bss <- round(rep(pokemon_against_km$betweenss, k), 2)

# n observations per cluster
nobs <- pokemon_against_km$size

# number of observations with negative sil value (misclassified)
neg_sil <- rep(0, k)

neg_sil_clust <- pokemon_against_km$silinfo$widths[, c("cluster","sil_width")] %>% 
  filter(sil_width < 0) %>% 
  group_by(cluster) %>% 
  summarize(neg_sil = n())

neg_sil[neg_sil_clust$cluster] <- neg_sil_clust$neg_sil 

table_data <- data.frame(clust_num, nobs, wss, bss, neg_sil) 

table_data %>% 
  datatable(rownames = FALSE, 
            colnames= c("Cluster", "N", "Within SS", "Between SS", "Neg. Silhouette"),
            caption = htmltools::tags$caption(
              style = 'caption-side: bottom; text-align: left;',
              htmltools::em('N = number of observations per cluster; SS = sum of squares')))

#AAC: That's an AWESOME table. Great job! 
```

